"""Core utilities for the PMARLO web application."""

from app.core.constants import DEEPTICA_SKIP_MESSAGE
from app.core.context import AppContext, build_context
from app.core.logging import configure_file_logging
from app.core.parsers import (
    format_lag_sequence,
    format_tau_schedule,
    parse_lag_sequence,
    parse_tau_schedule,
    parse_temperature_ladder,
)
from app.core.session import (
    ASSET_BUILD_SELECTION,
    ASSET_CONF_SELECTION,
    ASSET_MODEL_SELECTION,
    ASSET_RUN_SELECTION,
    ASSET_SHARD_SELECTION,
    ITS_FEEDBACK,
    ITS_PENDING_FEATURE_SPEC,
    ITS_PENDING_TOPOLOGY,
    LAST_BUILD,
    LAST_CONFORMATIONS,
    LAST_ITS_RESULT,
    LAST_SHARDS,
    LAST_SIM,
    LAST_TRAIN,
    LAST_TRAIN_CONFIG,
    MODEL_PREVIEW_RESULT,
    MODEL_PREVIEW_SELECTION,
    RUN_PENDING,
    TRAIN_CONFIG_PENDING,
    TRAIN_FEEDBACK,
    apply_analysis_config_to_state,
    apply_training_config_to_state,
    consume_pending_training_config,
    ensure_session_defaults,
    sync_form_metastable_states,
    sync_form_tica_dim,
    sync_sidebar_metastable_states,
    sync_sidebar_tica_dim,
    update_state,
)
from app.core.tables import (
    builds_dataframe,
    conformations_dataframe,
    metrics_table,
    models_dataframe,
    runs_dataframe,
    shards_dataframe,
    timescales_dataframe,
)
from app.core.view_helpers import (
    default_feature_spec_path,
    format_run_selection_summary,
    infer_default_topology,
    model_entry_label,
    render_conformations_result,
    render_deeptica_summary,
    select_shard_paths,
    show_build_outputs,
    summarize_selected_shards,
)

__all__ = [
    # Constants
    "DEEPTICA_SKIP_MESSAGE",
    # Context
    "AppContext",
    "build_context",
    # Logging
    "configure_file_logging",
    # Parsers
    "parse_temperature_ladder",
    "parse_lag_sequence",
    "parse_tau_schedule",
    "format_tau_schedule",
    "format_lag_sequence",
    # Session
    "ensure_session_defaults",
    "update_state",
    "consume_pending_training_config",
    "apply_training_config_to_state",
    "apply_analysis_config_to_state",
    "sync_sidebar_tica_dim",
    "sync_form_tica_dim",
    "sync_sidebar_metastable_states",
    "sync_form_metastable_states",
    # Session state keys
    "LAST_SIM",
    "LAST_SHARDS",
    "LAST_TRAIN",
    "LAST_TRAIN_CONFIG",
    "LAST_BUILD",
    "RUN_PENDING",
    "TRAIN_CONFIG_PENDING",
    "TRAIN_FEEDBACK",
    "LAST_CONFORMATIONS",
    "LAST_ITS_RESULT",
    "ITS_FEEDBACK",
    "MODEL_PREVIEW_SELECTION",
    "MODEL_PREVIEW_RESULT",
    "ASSET_RUN_SELECTION",
    "ASSET_SHARD_SELECTION",
    "ASSET_MODEL_SELECTION",
    "ASSET_BUILD_SELECTION",
    "ASSET_CONF_SELECTION",
    "ITS_PENDING_TOPOLOGY",
    "ITS_PENDING_FEATURE_SPEC",
    # Tables
    "timescales_dataframe",
    "runs_dataframe",
    "shards_dataframe",
    "models_dataframe",
    "builds_dataframe",
    "conformations_dataframe",
    "metrics_table",
    # View helpers
    "select_shard_paths",
    "format_run_selection_summary",
    "summarize_selected_shards",
    "default_feature_spec_path",
    "infer_default_topology",
    "model_entry_label",
    "show_build_outputs",
    "render_deeptica_summary",
    "render_conformations_result",
]
