"""Core utilities for the PMARLO web application."""

from core.constants import DEEPTICA_SKIP_MESSAGE
from core.context import AppContext, build_context
from core.logging import configure_file_logging
from core.parsers import (
    _format_lag_sequence as format_lag_sequence,
    _format_tau_schedule as format_tau_schedule,
    _parse_lag_sequence as parse_lag_sequence,
    _parse_tau_schedule as parse_tau_schedule,
    _parse_temperature_ladder as parse_temperature_ladder,
)
from core.session import (
    _ASSET_BUILD_SELECTION as ASSET_BUILD_SELECTION,
    _ASSET_CONF_SELECTION as ASSET_CONF_SELECTION,
    _ASSET_MODEL_SELECTION as ASSET_MODEL_SELECTION,
    _ASSET_RUN_SELECTION as ASSET_RUN_SELECTION,
    _ASSET_SHARD_SELECTION as ASSET_SHARD_SELECTION,
    _ITS_FEEDBACK as ITS_FEEDBACK,
    _ITS_PENDING_FEATURE_SPEC as ITS_PENDING_FEATURE_SPEC,
    _ITS_PENDING_TOPOLOGY as ITS_PENDING_TOPOLOGY,
    _LAST_BUILD as LAST_BUILD,
    _LAST_CONFORMATIONS as LAST_CONFORMATIONS,
    _LAST_ITS_RESULT as LAST_ITS_RESULT,
    _LAST_SHARDS as LAST_SHARDS,
    _LAST_SIM as LAST_SIM,
    _LAST_TRAIN as LAST_TRAIN,
    _LAST_TRAIN_CONFIG as LAST_TRAIN_CONFIG,
    _MODEL_PREVIEW_RESULT as MODEL_PREVIEW_RESULT,
    _MODEL_PREVIEW_SELECTION as MODEL_PREVIEW_SELECTION,
    _RUN_PENDING as RUN_PENDING,
    _TRAIN_CONFIG_PENDING as TRAIN_CONFIG_PENDING,
    _TRAIN_FEEDBACK as TRAIN_FEEDBACK,
    _apply_analysis_config_to_state as apply_analysis_config_to_state,
    _apply_training_config_to_state as apply_training_config_to_state,
    _consume_pending_training_config as consume_pending_training_config,
    _ensure_session_defaults as ensure_session_defaults,
    _sync_form_metastable_states as sync_form_metastable_states,
    _sync_form_tica_dim as sync_form_tica_dim,
    _sync_sidebar_metastable_states as sync_sidebar_metastable_states,
    _sync_sidebar_tica_dim as sync_sidebar_tica_dim,
    _update_state as update_state,
)
from core.tables import (
    _builds_dataframe as builds_dataframe,
    _conformations_dataframe as conformations_dataframe,
    _metrics_table as metrics_table,
    _models_dataframe as models_dataframe,
    _runs_dataframe as runs_dataframe,
    _shards_dataframe as shards_dataframe,
    _timescales_dataframe as timescales_dataframe,
)
from core.view_helpers import (
    _default_feature_spec_path as default_feature_spec_path,
    _format_run_selection_summary as format_run_selection_summary,
    _infer_default_topology as infer_default_topology,
    _model_entry_label as model_entry_label,
    _render_conformations_result as render_conformations_result,
    _render_deeptica_summary as render_deeptica_summary,
    _select_shard_paths as select_shard_paths,
    _show_build_outputs as show_build_outputs,
    _summarize_selected_shards as summarize_selected_shards,
)

__all__ = [
    # Constants
    "DEEPTICA_SKIP_MESSAGE",
    # Context
    "AppContext",
    "build_context",
    # Logging
    "configure_file_logging",
    # Parsers
    "parse_temperature_ladder",
    "parse_lag_sequence",
    "parse_tau_schedule",
    "format_tau_schedule",
    "format_lag_sequence",
    # Session
    "ensure_session_defaults",
    "update_state",
    "consume_pending_training_config",
    "apply_training_config_to_state",
    "apply_analysis_config_to_state",
    "sync_sidebar_tica_dim",
    "sync_form_tica_dim",
    "sync_sidebar_metastable_states",
    "sync_form_metastable_states",
    # Session state keys
    "LAST_SIM",
    "LAST_SHARDS",
    "LAST_TRAIN",
    "LAST_TRAIN_CONFIG",
    "LAST_BUILD",
    "RUN_PENDING",
    "TRAIN_CONFIG_PENDING",
    "TRAIN_FEEDBACK",
    "LAST_CONFORMATIONS",
    "LAST_ITS_RESULT",
    "ITS_FEEDBACK",
    "MODEL_PREVIEW_SELECTION",
    "MODEL_PREVIEW_RESULT",
    "ASSET_RUN_SELECTION",
    "ASSET_SHARD_SELECTION",
    "ASSET_MODEL_SELECTION",
    "ASSET_BUILD_SELECTION",
    "ASSET_CONF_SELECTION",
    "ITS_PENDING_TOPOLOGY",
    "ITS_PENDING_FEATURE_SPEC",
    # Tables
    "timescales_dataframe",
    "runs_dataframe",
    "shards_dataframe",
    "models_dataframe",
    "builds_dataframe",
    "conformations_dataframe",
    "metrics_table",
    # View helpers
    "select_shard_paths",
    "format_run_selection_summary",
    "summarize_selected_shards",
    "default_feature_spec_path",
    "infer_default_topology",
    "model_entry_label",
    "show_build_outputs",
    "render_deeptica_summary",
    "render_conformations_result",
]
