# .pre-commit-config.yaml
minimum_pre_commit_version: "3.0.0"

repos:
  # ───────────── Uniwersalne checki tekstowe ─────────────
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # ───────────── Formatter Black ─────────────
  # ───────────── Use tox for code style checks ─────────────
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        args: ["--check"]
        additional_dependencies:
          - black==25.1.0
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        args: ["--check-only"]
        additional_dependencies:
          - isort==6.0.1
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        additional_dependencies:
          - flake8==7.1.0

  # ───────────── Statyczna analiza typów (mypy) ─────────────
  - repo: local
    hooks:
      - id: mypy
        name: mypy (poetry)
        entry: poetry
        language: system
        pass_filenames: false
        args:
          - run
          - mypy
          - src/pmarlo

  - repo: local
    hooks:
      - id: pytest-fast
        name: pytest fast (unit changed)
        entry: poetry run pytest --testmon -q -m "unit and not slow"
        language: system
        pass_filenames: false
        stages: [pre-commit]
