apiVersion: batch/v1
kind: Job
metadata:
  name: pmarlo-algo-tests
spec:
  completions: 6           # 3 tryby (simulation, remd, msm) x 2 warianty
  parallelism: 3           # ile zadań naraz (dostosuj do klastra)
  completionMode: Indexed
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: experiments-output
        persistentVolumeClaim:
          claimName: pmarlo-experiments-pvc
      containers:
      - name: runner
        image: pmarlo-exp:dev
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: experiments-output
          mountPath: /app/output
          subPathExpr: $(JOB_COMPLETION_INDEX)
        env:
        - name: PMARLO_OUTPUT_ROOT
          value: /app/output
        - name: JOB_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        # Predefined suite uses tests/_assets and standard output roots; no extra env needed
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
