apiVersion: v1
kind: Pod
metadata:
  name: copy-helper
spec:
  restartPolicy: Never
  containers:
  - name: c
    image: busybox
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - name: vo
      mountPath: /data
  volumes:
  - name: vo
    persistentVolumeClaim:
      claimName: pmarlo-experiments-pvc
