from __future__ import annotations

from typing import Any, Dict, Optional

import numpy as np
import pandas as pd


class ExportMixin:
    def save_analysis_results(self, prefix: str = "msm_analysis") -> None: ...

    def _save_transition_matrix(self, prefix: str) -> None: ...

    def _save_count_matrix(self, prefix: str) -> None: ...

    def _save_free_energies(self, prefix: str) -> None: ...

    def _save_stationary_distribution(self, prefix: str) -> None: ...

    def _save_discrete_trajectories(self, prefix: str) -> None: ...

    def _save_state_table_file(self, prefix: str) -> None: ...

    def _save_fes_array(self, prefix: str) -> None: ...

    def _save_free_energy_bar_plot(self, prefix: str) -> None: ...

    def _log_save_completion(self) -> None: ...
